### ISSUE TITLE
Fails to download regions, claims "missing executable"

### ISSUE THREAD

**Issue by LeechesG** [Garrakx/Custom-Regions#129]
Simple as. I have looked into the readme and have no idea what executable it could be referring to. I have all dependencies listed and have tried verifying my game files, yet the issue persists. It also continutes to think it is downloading a region, forcing me to close the game entirely if I want to leave the configmachine page, and not allowing me to retry the download.

**Comment by LeechesG** [comment]
Issue resolved. This mod not compatable with Partiality, as it appears to search for a mod loader .exe (which Partiality does not have as a .bat). BepInEx slightly more required than recommended.

**Comment by Garrakx** [comment]
CRS is compatible with Partiality, and does not try to search for the mod loader .exe as you say. CRS uses a separate application to download the regions, which it is explained in the FAQ section of the [README.](https://github.com/Garrakx/Custom-Regions#FAQ)
It seems somehow the `RegionPackDownloader.exe` did not download in your case. It also appears that switching to BepInEx solved your issue, which it is recommended since Partiality is now abandoned and it is known to cause unexpected issues.

**Comment by Akihakira616** [comment]
I have a same problem, but i use BOI. When i try to download a region, he told me "missing executable" but i have all executable
